Feature/settings view ui
mash-up-kr/Constellation-Diary-iOS pull request #37
Opened 2019-12-21 17:27 UTC by heyKaren

설정화면 추가~!

2019-12-21 18:57 UTC, O-O-wl requested changes

2019-12-21 18:57 UTC, O-O-wl commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +        self.dismiss(animated: true, completion: nil)
저도 self 참 좋아합니다만 ✨
지우는걸루~.~

2019-12-21 18:57 UTC, O-O-wl commented on StarStarDiary/Views/BaseTableViewCell.swift
> +    public func setEntity(cell: SettingsViewCellItem) {
살짝 메소드 파라미터 라벨이  어색하게 느껴지는 것 같아여

2019-12-21 18:57 UTC, O-O-wl commented on StarStarDiary/Views/BaseTableViewCell.swift
> +    required init?(coder: NSCoder) {
주석은 삭제하는 걸루~.~

2019-12-21 18:57 UTC, O-O-wl commented on StarStarDiary/Views/BaseTableViewCell.swift
> +    // MARK: - Init
init() 이  MARK: - Life Cycle 에 포함되어 있어서 조금 어색한거 같아용?

2019-12-21 18:57 UTC, O-O-wl commented on StarStarDiary/Views/BaseTableViewHeaderFooterView.swift
> +    convenience init() {
이 `convenience init` 이 어떨 때 필요한 걸까여?

2019-12-21 18:57 UTC, O-O-wl commented on StarStarDiary/Views/BaseTableViewHeaderFooterView.swift
> +        if title == "" {
isEmpty 로 표현하는 걸 더 권장하는 것으로 알고 있습니당

2019-12-21 18:57 UTC, O-O-wl commented on StarStarDiary/Views/BaseTableViewHeaderFooterView.swift
> +        self.addSubview(baseView)
여기는 self 붙이는게 명확해 보이긴 하는데 
음 어떡하지 ㅎ ㅡㅎ 있는게 좋아보이는거 같긴한데ㅔㅔ

2019-12-21 18:57 UTC, O-O-wl commented on StarStarDiary/ViewControllers/SettingsViewController+cell.swift
> +    var isHiddenBottomLine: Bool
셀에서 사용되야하는 필수 아이템과 아닌걸 구분하는 건 어떨까요?

subTitle이나 isSwichOn 같은건 특정 셀에서는 없는 데이터 인거 같아요
이런건 `Optional` 타입으로 하는 건 어떨까요?

```swift
 var subTitleString: String {
             switch self {
             case .amAlerm,
                  .pmAlarm,
                  .changePMAlaramTime,
                  .logout: return ""
             case .appVersion: return "ver \(Bundle.main.appVersion)"
             }
         }
```

같은 불필요한 데이터를 넣는 걸 막을 수 있을 거같아요

2019-12-21 18:57 UTC, O-O-wl commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +    }
items에서 section 에 접근하는 방법이 다른거 같아요 혹시 이유가 있을까요?

2019-12-21 18:57 UTC, O-O-wl commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +        return 0.0
early exit을 하는 guard 도 적절해 보이긴 하는데 어떻게 생각하시나영

2019-12-21 18:57 UTC, O-O-wl commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +        items = SettingsViewItem()
인스턴스 프로퍼티에  `var item: SettingViewItem!`으로 정의해두고 여기서 생성하는데 혹시 이유가 있을까여?

`var item = SettinngViewItem()` 
으로 해도 됬을 거 같아요

2019-12-21 18:57 UTC, O-O-wl commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +    private func initVar() {
팩토리 형태의 네이밍도 좋을 거같아요 
메소드 명이 살짝 불명확해보이는 것 같아요

2019-12-21 19:01 UTC, O-O-wl requested changes

2019-12-21 19:01 UTC, O-O-wl commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +        tableView.deselectRow(at: indexPath, animated: true)
셀들중에 선택되지 않아야할 셀들이 있는 것 같아요
`cell.selectionStyle = .none` 형태로 선택에 대한 효과가 없게 구현할 수 있어요
0,1,4 인덱스의 셀은 선택불가능하게 하는 건 어떨까요?
<img width="305" alt="스크린샷 2019-12-22 오전 3 59 59" src="https://user-images.githubusercontent.com/39197978/71312537-87690d00-246f-11ea-88f9-4a15618306a2.png">

2019-12-22 01:45 UTC, heyKaren commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +        self.dismiss(animated: true, completion: nil)
예아~.~

2019-12-22 01:46 UTC, heyKaren commented on StarStarDiary/Views/BaseTableViewCell.swift
> +    public func setEntity(cell: SettingsViewCellItem) {
'cell:'  이것을 말씀하시는게 맞나여? 어떤 부분이 어색한지 말씀해주십시5!

2019-12-22 01:48 UTC, heyKaren commented on StarStarDiary/Views/BaseTableViewCell.swift
> +    // MARK: - Init
view에 의해서 자동적으로 불리는 부분이라  Life Cycle 에 넣긴 했는데,
MARK: - Init 쪽으로 옮기게되면 함수를 불러서 설정하는 부분들이랑 섞이는데 괜찮을까유??

2019-12-22 02:01 UTC, heyKaren commented on StarStarDiary/Views/BaseTableViewHeaderFooterView.swift
> +    convenience init() {
self.init() 요 아이를 부르기 위해서 필요했씁니다

2019-12-22 02:08 UTC, heyKaren commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +    }
어떤 부분과의 방법이 다른 것을 물어보시는걸까요??

2019-12-22 02:10 UTC, heyKaren commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +        items = SettingsViewItem()
전역에서 생성하는것 피하려고 한 건가바여 
`var item = SettinngViewItem()`
요게 더 깔끔할것같네요! 수정 고고딩

2019-12-22 02:11 UTC, heyKaren commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +    private func initVar() {
팩토리 형태라면 어떤게 있을까요?
저 함수 네이밍은 전역에 선언되는 변수들의 값을 초기화해준다는 의미로 작성하였습니다!

2019-12-22 02:22 UTC, heyKaren commented on StarStarDiary/Views/BaseTableViewHeaderFooterView.swift
> +        if title == "" {
헐 몰랏어여 감삼다

2019-12-22 02:23 UTC, heyKaren commented on StarStarDiary/Views/BaseTableViewHeaderFooterView.swift
> +        self.addSubview(baseView)
그 아랫줄에  다른 뷰에 addSubview 하는게 있어서,
직관적인 느낌으로다가 이대로 가는 것이 어떻숨미까?

2019-12-22 17:26 UTC, O-O-wl commented on StarStarDiary/Views/BaseTableViewCell.swift
> +    public func setEntity(cell: SettingsViewCellItem) {
Cell 의 메소드인데 cell을 파라미터로 받는다는게 어색한거같아요
셀에 매칭대는 데이터?라는 의미가 내포되면 좋을거같아요

2019-12-22 17:28 UTC, O-O-wl commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +    }
섹션을 이터레이팅을 하며 인덱스와 일치하는 걸 으로 접근하는 경우와
인덱스로 바로 접근하는 차이가 있는거같아여

2019-12-22 17:31 UTC, O-O-wl commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +    private func initVar() {
Create 나 make 의 형태의 메소드 네이밍을 생각했엇습니당

2019-12-22 17:33 UTC, O-O-wl commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +    private func initVar() {
다른 initView와 같은 메소드와의 일관성을 위해서는 지금처럼 해도 괜찮을것같긴합니당

2019-12-22 17:33 UTC, O-O-wl commented on StarStarDiary/Views/BaseTableViewHeaderFooterView.swift
> +        self.addSubview(baseView)
주희누나랑도 얘기해봐영

2019-12-23 13:54 UTC, caution-dev commented on StarStarDiary/ViewControllers/SettingsViewController+cell.swift
> +            case .appVersion: return .hasSubTitle
오홍 요렇게 보니까 가독성이 떨어지는 것 같아서 한 줄 내리는 건 어떤가요?

2019-12-23 13:56 UTC, caution-dev commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +    private func initVar() {
`initItems`나 `initCells` 음~? `initVar`는 좀 애매한 것 같아용

2019-12-23 13:57 UTC, caution-dev commented on StarStarDiary/ViewControllers/SettingsViewController.swift
> +        let view = tableView.dequeueReusableHeaderFooterView(withIdentifier: "BaseTableViewHeaderFooterView") as! BaseTableViewHeaderFooterView
강제 언래핑을 줄여보는 건 어때요~

2019-12-23 13:57 UTC, caution-dev commented on StarStarDiary/Views/BaseNavigationView.swift
> +                make.trailing.equalTo(btnRight.snp.leading).inset(-16.0)
inset 대신 offset~?

2019-12-23 14:04 UTC, caution-dev commented on StarStarDiary/Views/BaseNavigationView.swift
> +        }
묶어줘엉

2019-12-23 14:08 UTC, caution-dev commented on StarStarDiary/Views/BaseTableViewHeaderFooterView.swift
> +        self.addSubview(baseView)
우리가 맞다고 생각하는 거면 킵고잉~~~!! 다만 좀 헷갈리니까 @O-O-wl 위키에 self 사용에 대해 정리해주세욤

2019-12-23 14:10 UTC, caution-dev commented on StarStarDiary/Views/BaseTableViewCell.swift
> +                $0.bottom.equalToSuperview()
수정 코멘트~!

2019-12-23 14:19 UTC, caution-dev commented on StarStarDiary/Views/BaseTableViewCell.swift
> +    public func setEntity(cell: SettingsViewCellItem) {
`bindSetting(item:)`정도는 어때요

2020-01-31 10:46 UTC, merged